project:
  type: book

book:
  title: "Portfolio"
  author: "Madeleine Potter"
  date: "25/04/2024"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
        listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - page.qmd

bibliography: references.bib

format:
  html:
    theme: yeti
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual

output-dir: docs